[package]
name = "write_atomic"
version = "0.2.9"
authors = ["Blobfolio, LLC. <hello@blobfolio.com>"]
edition = "2021"
rust-version = "1.56"
description = "Write to files atomically."
license = "WTFPL"
repository = "https://github.com/Blobfolio/write_atomic"
readme = "README.md"
exclude = [
	".github",
	".gitignore",
	".righteous-sandbox.json",
	"doc",
	"justfile",
	"release",
]

[package.metadata.bashman]
name = "write_atomic"
bash-dir = "./"
man-dir = "./"
credits-dir = "./"

[dependencies]
fastrand = ">=1.7.0, <=1.9.0"
tempfile = "=3.3.0"

[target.'cfg(unix)'.dependencies]
libc = ">= 0.2.34"
