[package]
name = "write_atomic"
version = "0.2.10"
authors = ["Blobfolio, LLC. <hello@blobfolio.com>"]
edition = "2021"
rust-version = "1.56"
description = "Write to files atomically."
license = "WTFPL"
repository = "https://github.com/Blobfolio/write_atomic"
readme = "README.md"
exclude = [
	".github",
	".gitignore",
	".righteous-sandbox.json",
	"doc",
	"justfile",
	"release",
]

[package.metadata.bashman]
name = "write_atomic"
bash-dir = "./"
man-dir = "./"
credits-dir = "./"

[dependencies]
tempfile = "=3.4.0"

[target.'cfg(unix)'.dependencies.rustix]
version = "0.36.0" # Match the version required by tempfile.
features = [ "fs", "process" ]
